//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsDatabaseDiscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENTS
    {
        public int ID { get; set; }
        public string STUDENT_NUMBER { get; set; }
        public string STUDENT_NAME { get; set; }
        public string STUDENT_ADDRESS { get; set; }
        public int STUDENT_YEAR_LEVEL { get; set; }
        public string STUDENT_CONTACT_NUMBER { get; set; }
        public bool STATUS { get; set; }
    }
}
