//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsDatabaseDiscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMINS
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    }
}
